name: bmi_calculator_v1
description: "It Is A Simple BMI Calculator By Flutter. Body Mass Index (BMI) is a widely used measurement that assesses body fat based on an individual's height and weight."

publish_to: "none"

homepage: https://github.com/KASRA10/BMI-Calculator_V1.git
issue_tracker: https://github.com/KASRA10/BMI-Calculator_V1.git
documentation: https://github.com/KASRA10/BMI-Calculator_V1.git
repository: https://github.com/KASRA10/BMI-Calculator_V1.git

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #         style: italic
